### ISSUE TITLE
Let Tarrastate take care of workspaces

### ISSUE THREAD

**Issue by PierreKerschgens** [janritter/terrastate#3]
What about (optional) storing the preferred workspace in the given var file and let terrastate do the workspace selection.

You could append this variable to env/dev.tfvars:
`state_workspace = "dev"`

Then instead of using:
`terraform workspace select dev`
`terraform plan -var-file=env/dev.tfvars`

Use (requires implementation of #2):
`terrastate plan -var-file=env/dev.tfvars`

**Comment by janritter** [comment]
Terrastate should eliminate the need for workspaces, instead different keys should be use
